# Generated by Django 5.2.8 on 2025-11-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du Mémoire')),
                ('auteur', models.CharField(max_length=150, verbose_name="Nom(s) de l'Auteur(s)")),
                ('annee', models.IntegerField(verbose_name='Année de Soutenance')),
                ('filiere', models.CharField(max_length=50, verbose_name='Filière (Ex: GI, GM, GC)')),
                ('axe_recherche', models.CharField(blank=True, max_length=100, null=True, verbose_name='Axe de Recherche')),
                ('fichier_pdf', models.FileField(upload_to='memoires/pdfs/', verbose_name='Fichier PDF')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_soumission'],
            },
        ),
    ]
